# Utilizar la imagen base de MySQL
FROM mysql:8

# Variables de entorno para configurar el usuario y la contraseña de la base de datos
ENV MYSQL_ROOT_PASSWORD=1234
ENV MYSQL_DATABASE=prueba_db
ENV MYSQL_USER=enoc
ENV MYSQL_PASSWORD=1234

# Copiar el script SQL para inicializar la base de datos
COPY script.sql /docker-entrypoint-initdb.d/

# Exponer el puerto del servidor MySQL (por defecto es 3306)
EXPOSE 3306
