version: "3.1"
services:
  miappenoc:
    container_name: miapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - reddepruebas

networks:
  reddepruebas:
    external: true
